language: go

go:
  - 1.2
  - 1.1

install:
  - sudo apt-get install -y autoconf libtool automake build-essential libglib2.0-dev libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler
  - go get code.google.com/p/goprotobuf/proto
  - go get code.google.com/p/goprotobuf/protoc-gen-go

env:
  - PATH=$GOPATH/bin:$GOROOT/bin:$PATH

script:
  - sudo cp /home/travis/gopath/bin/protoc-gen-go /usr/local/bin
  - make all
